### PR TITLE
Dutch translation (Nederlands)

### PR DESCRIPTION
**Pull request by erik-am**
```
E-mail address: e.ammerlaan@outlook.com
Name: Erik Ammerlaan
LanguageID: nl
LanguageName: Dutch
DisplayName: Nederlands
Version used for testing: 1.2.0 and 1.3.4 and 1.4.1
```
### Summary of approach

I translated the English sentences to Dutch. Then I verified in the game if it looked correct. In some cases I adjusted the coordinates a couple of times until it was okay (because translated sentences are sometimes longer than the original ones). Sometimes I used the German font sizes and coordinates as inspiration, as both Dutch and German generally have longer sentences than the English source. For the order of translating files, I grouped them by location (Farley's house, C.W. Workshop, et cetera) so that verifying the translations in-game was easier. For the replayable speeches I also replayed those in-game to see if the subtitles could be read quickly enough by the player.

### TODO
- [X] AmbassadorSeed.json
- [x] ArrivalInventory.json
- [x] BarnacleProject.json
- [X] BatteryLog.json
- [x] Bleeder.json
- [x] Bleeder_b.json
- [x] Blob.json
- [x] blob2.json
- [x] Board.json
- [X] CarolineLetter.json
- [x] Communication.json
- [x] CW_180A.json
- [x] CW_180B.json
- [x] CW_180C.json
- [x] CW_180D.json
- [x] CW_180E.json
- [x] CW_BleederA.json
- [x] CW_BleederB.json
- [x] CW_BleederC.json
- [x] CW_Connect1A.json
- [x] CW_Connect1B.json
- [x] CW_Connect1C.json
- [x] CW_Connect2A.json
- [x] CW_Connect2B.json
- [x] CW_Connect2C.json
- [x] CW_Final1A.json
- [x] CW_Final1B.json
- [x] CW_FinalDia.json
- [x] CW_FinalEar.json
- [x] CW_PowerA.json
- [x] CW_PowerB.json
- [x] CW_PowerC.json
- [x] CW_PowerD.json
- [x] EECodeTest.json
- [x] FarleyImagerTest_Mono.json
- [x] FarleyTapeIntro.json
- [x] FarleyVaultJournal.json
- [x] Farley_Audio_Journal.json
- [x] FY_VilleinMessage.json
- [x] GuestBook.json
- [x] HR_Town_New.json
- [x] HR_Tree_New.json
- [x] HR_Water_New.json
- [x] HR_Welcome_New.json
- [x] HunrathHistoryScrap1.json
- [x] HunrathHistoryScrap1b.json
- [x] IM_EX3.json
- [x] IM_HU1.json
- [x] IM_HU2.json
- [x] IM_HU3.json
- [x] IM_HU4.json
- [x] IM_Intro.json
- [x] Intro1_A.json
- [x] Intro1_B.json
- [x] Intro1_C.json
- [x] Intro2_A.json
- [x] Intro2_B.json
- [x] Intro2_C.json
- [x] Intro2_D.json
- [x] Intro2_E.json
- [x] Intro2_F.json
- [x] Intro2_G.json
- [x] Intro2_H.json
- [x] Intro2_I.json
- [x] Intro3_A.json
- [x] Intro3_B.json
- [x] Intro3_C.json
- [x] Intro4_A.json
- [x] Intro4_B.json
- [x] Intro4_C.json
- [X] KioskFarley.json
- [X] Lockdown.json
- [x] Manifest.json
- [x] Manifest_test.json
- [X] MayorImager.json
- [x] MayorsLog.json
- [X] Menu.json
- [X] MofangDisabler.json
- [X] MofangProjector.json
- [x] RacesHistory.json
- [x] SeedInformation.json
- [x] TheGauntlet.json
- [x] ThePlan.json
- [X] VaultClue.json
- [X] WMDWarning1.json
- [X] WMDWarning1_b.json
- [X] wmdwarning2.json

### CODE REVIEW

**Comment by hgamiel** [comment]
This is awesome! Thank you so much. I'm definitely looking forward to seeing the finished product.

**Comment by erik-am** [comment]
@hgamiel I noticed that in version 1.3.4 the English Menu.json got some updates. Now it's possible to translate the "Speed: Walk/Run" notifcations, thanks! Made some changes there.

I hope to have the final translations ready in about two weeks. Meanwhile my relatives are beta-testing the translations so far and they like it a lot: they can spend their brain power at actually solving puzzles instead of translating documents in their heads. 😀 

I hope the final version of the translation will make it on the physical boxed edition for the Backers.

**Comment by hgamiel** [comment]
Thanks for all of your changes (and thorough testing :-) ), @erik-am. The two week time period might work out for us. I will contact you if we need them before that time.

**Comment by erik-am** [comment]
It's done!! 😄

**Pull request merged**
